name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      #  Uncomment the branches below to enable the workflow
      # - main
      # - master
    paths:
      - "pyproject.toml"

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    # if this is a forked repository. Skipping the workflow.
    if: github.event.repository.fork == false 
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@main
        with:
          ## Add your own personal access token to your Github Repository secrets and reference it here.
          ## Get your personal access token from https://docs.comfy.org/registry/publishing#create-an-api-key-for-publishing
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
